# Python NumPy II
## Slicing and dicing

In [1]:
import numpy as np

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [3]:
X= np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
# specifying indices from rows, and next specifuing indices from columns
#starting index is included and ending is excluded
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
#not including ending index makes it all the way to the end
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [6]:
z= X[:3, :2]
print(z)

[[ 1  2]
 [ 6  7]
 [11 12]]


In [8]:
#alll the elements in colmn 3
z= X[:, 2]
print(z)

[ 3  8 13 18]


In [9]:
# select all the elements in column 3 but in a rank 2 array
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In all the above slices of X that are "stored" in z, are not actually stored and copied in z, they are just references of X or just different names of the same array. **Slicing just creates a *view* of the original array**.
So changing any elements in z will change in X too. To create a copy, we need to use the `np.copy` function.

In [10]:
z= X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [11]:
z[2,2] = 155
print('z=\n',z)
print('X=\n',X)#impacted by the change in z


z=
 [[  8   9  10]
 [ 13  14  15]
 [ 18  19 155]]
X=
 [[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 155]]


In [12]:
# using copy function
X= np.arange(1,21).reshape(4,5)
print(X)
z= np.copy(X[1:, 2:]) 
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [13]:
# using copy in diff way
X= np.arange(1,21).reshape(4,5)
print(X)
z= X[1:, 2:].copy()
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [14]:
#changin z now
z[2,2] = 155
print('z=\n',z)
print('X=\n',X)#not impacted by the change in z



z=
 [[  8   9  10]
 [ 13  14  15]
 [ 18  19 155]]
X=
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### Using one array as indices to select from another

In [15]:
indices = np.array([1,3])
print(indices)

[1 3]


In [17]:
y = X[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [18]:
z = X[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [21]:
print('X=\n',X)
z= np.diag(X)
print('z=\n',z)


X=
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
z=
 [ 1  7 13 19]


In [22]:
#elements above the main diagonal, specify k, default k=0
z= np.diag(X,k=1)
print('z=\n',z)

z=
 [ 2  8 14 20]


#### Unique elements array

In [23]:
# an array with repeated values
X = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(X)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [24]:
#unique values
print(np.unique(X))

[1 2 3 4 5 6]


## Boolean indexing, Set Operations, and Sorting
Boolen indexing helps in scenarios when the indices are unknown, we can use it to select elements using logical arguments instead.

In [25]:
# elements from 0-24
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
#slect elements > 10
print(X[X>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [27]:
print(X[X<=7])

[0 1 2 3 4 5 6 7]


In [29]:
print(X[(X>10) & (X<17)])

[11 12 13 14 15 16]


In [31]:
# boolean indexing for assignments
X[(X>10)& (X<17)] = -1
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Set operations
We can create arrays for the intersection, union, and difference

In [32]:
x= np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.union1d(x,y))
print(np.setdiff1d(x,y))

[2 4]
[1 2 3 4 5 6 7 8]
[1 3 5]


#### Sorting
`sort` function can be used as a method as well. If sorting is done using `np.sort()` as a function, it does not change the original array. If `sort` is used as a method - `ndarray.sort()`, only then the contents of the original array are changed to sorted.

In [34]:
x= np.random.randint(1, 11, size = (10,))
print(x)

[10  1  7  9  2  6  1  7  1  5]


In [37]:
#using np.sort as function
print(np.sort(x))
print(x)
# and make elements unique
print(np.sort(np.unique(x)))

[ 1  1  1  2  5  6  7  7  9 10]
[ 1  1  1  2  5  6  7  7  9 10]
[ 1  2  5  6  7  9 10]


In [38]:
#using method
x.sort()
print(x)

[ 1  1  1  2  5  6  7  7  9 10]


In [39]:
# sorting rank 2 arrays
X = np.random.randint(1, 11, size= (5,5))
print(X)

[[ 3  7  3  4 10]
 [ 6  4  2  3  4]
 [ 9  9  2  2 10]
 [ 6  6  3  6  7]
 [ 9  7  6  4  7]]


In [40]:
# sort by rows
print(np.sort(X, axis =0))

[[ 3  4  2  2  4]
 [ 6  6  2  3  7]
 [ 6  7  3  4  7]
 [ 9  7  3  4 10]
 [ 9  9  6  6 10]]


In [41]:
#sort by columns
print(np.sort(X, axis=1))

[[ 3  3  4  7 10]
 [ 2  3  4  4  6]
 [ 2  2  9  9 10]
 [ 3  6  6  6  7]
 [ 4  6  7  7  9]]


### Arithematic operations and Broadcasting
Numpy allows element-wise operations as well as matrix operations.

In [42]:
x = np.array([1,2,3,4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [43]:
# element-wise operations : simple array  vs NumPy , the results are same
print(x+y) 
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [44]:
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In the element-wise arithematic operations such as above, NumPy uses Broadcasting. The arrays being operated on must have the same shape or be broadcastable.

In [46]:
# Same ops on rank 2 arrays
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print('X=\n',X)
Y = np.array([4, 5, 6, 7]).reshape(2, 2)
print('Y=\n',Y)

X=
 [[1 2]
 [3 4]]
Y=
 [[4 5]
 [6 7]]


In [47]:
print(X+Y)
print(X-Y)

[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [50]:
print(x)
#sqrt
print(np.sqrt(x))
#exp
print(np.exp(x))
# power of 2
print(np.power(x, 2))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]


#### Statistical functions using NumPy

In [54]:
print(X)
#average of X
print('Average of all: ', X.mean())
print('Average of rows:', X.mean(axis=0))
print('Average of columns:', X.mean(axis=1))
print('Std deviation :', X.std())
print('Median: ', np.median(X))
print('Max : ', X.max())
print('Min: ', X.min())

[[1 2]
 [3 4]]
Average of all:  2.5
Average of rows: [2. 3.]
Average of columns: [1.5 3.5]
Std deviation : 1.118033988749895
Median:  2.5
Max :  4
Min:  1


#### Broadcasting

In [55]:
# adding a single number to all the elements
print('X=',X)
print('X-3=', X-3)
print('3*X=', 3*x)

X= [[1 2]
 [3 4]]
X-3= [[-2 -1]
 [ 0  1]]
3*X= [ 3  6  9 12]


In [57]:
Y = np.arange(9).reshape(3,3)
print('Y=',Y)
x = np.arange(3)
print('x=',x)

Y= [[0 1 2]
 [3 4 5]
 [6 7 8]]
x= [0 1 2]


In the below cases NumPy expands the arrays so that it can broadcast.

In [61]:
print(Y+x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [59]:
z= np.arange(3).reshape(3,1)
print(z)

[[0]
 [1]
 [2]]


In [60]:
print(z+Y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
