# Python NumPy
**NumPy** or Numerical Python is a fundamental package for scientific computing in Python. It provides Python with extensive mathemetical libraries thus making it capable of performing numerical computations effectively and efficiently. Python can handle lists on its own, but **NumPy arrays** are faster thus providing an advantage when dealing with large arrays. Because NumPy arrays hold single type of data, thus the calculationg become much faster. NumPy also provides multi-dimensional data structures such as vectors and matrices that are highly used in Neural Networks. NumPy is very much optimized to handle matrix operations and allows us to do Linear Algebra very fast and efficiently, thus it is very much suitable for solving machine learning problems. 
NumPy also provides large number of built-in mathematical functions that are optimized and perform fast maathematical calculations. Infact, **Pandas** are also built using on top of **NumPy**.

In [6]:
#check the version of NumPy installed in your local
!conda list numpy

# packages in environment at /Users/nehatarey/opt/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
numpydoc                  0.9.2                      py_0  


#### Compare the difference between calculation times in Plain Python and NumPy

In [7]:
import time  #for time diff calc
import numpy as np

In [8]:
#generate 10 million random numbers
x = np.random.random(100000000)

In [9]:
#use plain python to calculate mean
start = time.time() #capture start time
sum(x)/len(x)
print(time.time()-start) #print the time diff

14.719552993774414


In [10]:
# use Numpy for mean calculation
start = time.time() # capture start time
np.mean(x)
print(time.time()-start) # print time diff

0.0673668384552002


The core of NumPy is the ndarray or n-dimensional array. The *ndarray* is a multi-dimensional array of all the same type of elements. It can hold either all strings or all numbers. There are multiple ways to create NumPy arrays. ndarrays can be created in two ways in NumPy :
- Using regular Python lists
- Using built-in NumPy functions

In [11]:
# 1st way 
import numpy as np

x = np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [14]:
x.dtype

dtype('int64')

In [15]:
x.shape # returns rows, col

(6,)

In [17]:
# 2-d array
y= np.array([[1,2,3],[4,5,6],[23,45,67],[4,7,8]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [23 45 67]
 [ 4  7  8]]


In [18]:
y.dtype

dtype('int64')

In [19]:
y.shape

(4, 3)

In [20]:
y.size

12

In [22]:
# rank 1 array of strings
x = np.array(['Hello', 'World'])
print(x)
print('shape :', x.shape)
print('type :', type(x))
print('dtype :',x.dtype)

['Hello' 'World']
shape : (2,)
type : <class 'numpy.ndarray'>
dtype : <U5


#### Upcasting
NumPy arrays that have mixed data types, NumPy upcasts the elements to ensure that all the data types in an array are of the same type. For eg, if an array has mixed integers and floats, NumPy will upgrade all the ints to floats. It does so to ensure precision in the mathematical calculations. We can manually assign a certain dtype to a NumPy array by specifying it while creating the array.

In [23]:
# mixed strings and numbers
x = np.array(['Hello','World',1])
print(x)
print('shape :', x.shape)
print('type :', type(x))
print('dtype :',x.dtype) # all the data tyoes are converted to unicode

['Hello' 'World' '1']
shape : (3,)
type : <class 'numpy.ndarray'>
dtype : <U5


In [24]:
#mixed ints and floats
x = np.array([1, 2, 3.5])
print(x)
print('shape :', x.shape)
print('type :', type(x))
print('dtype :',x.dtype) # everything is float now

[1.  2.  3.5]
shape : (3,)
type : <class 'numpy.ndarray'>
dtype : float64


In [25]:
# Manually assign a dtype to forcefully ensure that type of precision
x = np.array([1.2, 3.4, 5], dtype = np.int64)
print(x)
print('shape :', x.shape)
print('type :', type(x))
print('dtype :',x.dtype)

[1 3 5]
shape : (3,)
type : <class 'numpy.ndarray'>
dtype : int64


#### Save the array to file and load from file


In [27]:
x= np.array([1,2,3,4,5])
#following will save the array x in a file names my_array in the current working directory
np.save("my_array",x) # file is saved with extension .npy

In [29]:
#load an array from the saved file
y = np.load("my_array.npy")
print(y)

[1 2 3 4 5]


#### Creating ndarrays using built-in functions